[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Garante que o Prisma saiba onde gerar o client
  PRISMA_GENERATE_SKIP_AUTOINSTALL = "true"
  # Node 18+ conforme README
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"


